<?php

namespace AppBundle\Repository;

/**
 * SubsriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubsriptionRepository extends \Doctrine\ORM\EntityRepository
{
}
