<?php

namespace AppBundle\Repository;

/**
 * SubsriptionPaymentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubsriptionPaymentRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function findByCanceledSubscription()
    {
        $date = new \DateTime();
        $date->modify('-37 days');
        
        $result = $this->createQueryBuilder('t')
                ->andWhere('t.date < :date')
                ->setParameter(':date', $date)
                ->getQuery()
                ->execute();
        
        return $result;
    }
}
